### ISSUE TITLE
How can I bypass hackshlied? do you have an idea?

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/WarcraftHelper#1]
How can I bypass hackshlied? do you have an idea?
nexon eu cso turkey's client (Version: 2011 or 2013)
![image](https://user-images.githubusercontent.com/36341134/123342145-e40f2180-d557-11eb-9719-4e4c2e892423.png)
can you bypass the cso client if i send it to you (a private client)
please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3 please <3

https://drive.google.com/file/d/1XBmpWzhrCHSsW1zeqdKcaLiCfp5f-xZC/view
and can you just add the notification feature to the server?

**Comment by KouKouChan** [comment]
sorry, i have no idea
